version: "3"
services:
  frontend:
   build:
      context: ./frontend/
      dockerfile: dockerfile
   ports:
    -  3000:3000
   container_name: playground-frontend
   networks:
    -  mern-stack-net
   volumes:
    -  ./frontend/src:/usr/app/src
    -  ./frontend/public:/usr/app/public
   depends_on:
    - backend
   stdin_open: true
   tty: true

  backend:
   build:
      context: ./backend
      dockerfile: dockerfile
   ports:
     - 5000:5000
   environment:
      - SHORTNER_ENV=DOCKER
   container_name: playground-backend
   networks:
     - mern-stack-net
   volumes:
    - ./backend/src:/usr/app/src
   depends_on:
    - db

  db:
    image: mongo:4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME= root
      - MONGO_INITDB_ROOT_PASSWORD= rootpassword
      - MONGO_INITDB_DATABASE=shortner
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mern-stack-net
    volumes:
      #- ./db/data:/data/db
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

networks:
  mern-stack-net:
    driver: bridge